### ISSUE TITLE
[HELP] Installazione SENZA composer

### ISSUE THREAD

**Issue by MarcoRavich** [fatturaelettronicaphp/FatturaElettronica#100]
Buongiorno,
necessiterei sfruttare la vs. libreria per leggere i dati da fatture elettroniche caricate dagli utenti (formati XML e P7M) tramite interfaccia web ma, sebbene CREDO averla "installata" - in realtà solo caricata in una cartella via FTP, visto che ho un semplice hosting linux su Aruba - correttamente, non riesco a farla funzionare.

Potete aiutarmi ?

Grazie.

**Comment by MarcoRavich** [comment]
Ciao Daniele, anzitutto grazie per la risposta.

Ovviamente mi sono un po' documentato sul composer prima di chiedere, ma mi è sembrato più uno strumento per chi ha accesso alla consolle del server (locale o remoto che sia)...
...avendo un semplice spazio web (basato su linux ed accessibile via FTP), non posso quindi utilizzare questa libreria: ho capito bene ?

Il dubbio mi era venuto perchè invece sono riuscito, abbastanza agevolmente, ad "installare" ed utilizzare la [libreria CSV della "phpleague"](https://github.com/thephpleague/csv#csv) che pure [necessiterebbe del composer](https://github.com/thephpleague/csv?tab=readme-ov-file#install).

Grazie ancora anche per l'interessantissimo corso linkato.

**Comment by Skullbock** [comment]
Ciao Marco, è uguale :) 
la libreria la installi localmente nel tuo pc, e poi "carichi" i file via ftp, se quello è il modo in cui fai deployment.

Ti consiglio veramente la guida linkata al mio commento precedente, spiega proprio questi passaggi.
Concettualmetne usi composer sul tuo pc, fai `composer require` delle librerie che ti servono (es: anche phpleague csv) e sei proonto :)

**Comment by MarcoRavich** [comment]
> Ciao Marco, è uguale :)
la libreria la installi localmente nel tuo pc, e poi "carichi" i file via ftp, se quello è il modo in cui fai deployment.
>
...questo implicherebbe però avere un server Apache/PHP in locale replica di quello remoto, corretto ?

> Ti consiglio veramente la guida linkata al mio commento precedente, spiega proprio questi passaggi.
>
Certamente, anche se - avendo iniziato a vederlo - intuisco che sia appunto dato per scontato avere un server installato localmente (cosa che vorrei evitare).

Grazie ancora, buona giornata.

**Comment by Skullbock** [comment]
Ciao Marco, lo sviluppo (scusa la franchezza) si fa SEMPRE in locale, e poi quello di produzione è solo un suo "clone" con le specifiche :) Pensare di sviluppare direttamente da FTP, soprattutto senza accesso SSH, è alquanto difficile nel mondo php moderno (o di qualunque altro linguaggio). 

In bocca al lupo!

**Comment by MarcoRavich** [comment]
Allora, mi sono installato XAMPP e Composer e scarica/installa tutto (League CSV e fatturaelettronicaphp) correttamente.

Ma, mentre la prima libreria funziona, non capisco come richiamare (e quindi far funzionare) il parser della seconda...

Ecco il mio codice:
`require 'vendor/autoload.php';

use League\Csv\Writer; // funzioni di scrittura dei CSV 
use League\Csv\Reader; // funzioni di scrittura dei CSV
use Fatturaelettronicaphp\Fattura-elettronica\Parser\DigitalDocumentParser; // carica il parser per i XML/P7M`

...dove sbaglio ?

Grazie.
