### ISSUE TITLE
Problema con Tipo Cassa Previdenziale

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#102]
Ciao mi è capitato di ricevere una fattura con dati cassa previdenziale e ho riscontrato un problema mentre recuperavo il tipo cassa in quanto davo per scontato che getType() restituisse il campo "<TipoCassa>" (quindi una semplice STRING) ma in realtà mi restituisce un oggetto con TipoCassa e la sua descrizione. E quindi quando sono andato ad utilizzare la mia variabile $tipoCassaPrevidenziale per dei confronti, pensando fosse una semplice string, la mia app si è rotta.

    $funds = $instanceDocument->getFunds();
				
		foreach ( $funds as $fund ) {
			$tipoCassaPrevidenziale = $fund->getType();
                        var_dump($tipoCassaPrevidenziale);  // pensavo di ricevere solo "TC08"!
                        ...
                }

var_dump:

   object(FatturaElettronicaPhp\FatturaElettronica\Fund)[59]
     protected 'type' => 
       object(FatturaElettronicaPhp\FatturaElettronica\Enums\FundType)[60]
         public 'value' => string 'TC08' (length=4)
         public 'description' => string 'Ente nazionale previdenza e assistenza consulenti del lavoro (ENPACL)
                    ' (length=90)
     protected 'percentage' => float 4
     protected 'amount' => float 12.6
     protected 'subtotal' => float 315
     protected 'taxPercentage' => float 22
     protected 'deduction' => null
     protected 'vatNature' => null
     protected 'representative' => null

Per ovviare ho aggiunto al file Enum.php i seguenti 2 metodi:

    public function getValue(): string
    {
        return $this->value;
    }
	
	public function getDescription(): string
    {
        return $this->description;
    }

in modo da modificare il codice in:
 
    $tipoCassaPrevidenziale = $fund->getType()->getValue();

**Comment by Skullbock** [comment]
E' un Enum (fatto a mano, purtroppo pre php8.1 non ci sono gli enum, se ci sarà una nuova major release convertiremo tutto a `Enum` e php 8.2+) quindi hai già accesso a `value`.

```php
$funds = $instanceDocument->getFunds();
			
foreach ( $funds as $fund ) {
        $tipoCassaPrevidenziale = $fund->getType();
        $value = $tipoCassaPrevidenziale->value;
}
```

Puoi anche castarlo a stringa e funziona

```php
$value = (string) $tipoCassaPrevidenziale;
```
