### ISSUE TITLE
Uncaught Error: Interface 'Stringable' not found

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#26]
Installando il pacchetto con composer utilizzando PHP 7.4.9 ricevo questo errore una volta utilizzato il comando: $digitalDocument = DigitalDocument::parseFrom($xml);

Errore:
Fatal error: Uncaught Error: Interface 'Stringable' not found in .....
Error: Interface 'Stringable' not found in .... src\Enums\Enum.php

Modificando manualmente

     abstract class Enum implements Stringable, JsonSerializable

in:

     abstract class Enum implements JsonSerializable

Il problema sembra risolto

**Comment by Skullbock** [comment]
Grazie della segnalazione, abbiamo appena rilasciato la 2.1.1 con un fix per questo problema

Segnalo però che php 7.4.9 è una versione non aggiornata della serie 7.4, la cui ultima release ad oggi è 7.4.25, per cui consigliamo un veloce aggiornamento :)
