### ISSUE TITLE
Unable to read invoices from "Enel Energia S.p.A."

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#27]
Salve il fornitore Enel Energia S.p.A. utilizza un formato leggermente diverso nella creazione delle fatture p7m che è impossibile da leggere tramite il parsing php.
Anche tramite il vostro script il problema rimane.
Avete modo di provare delle fatture Enel Energia S.p.A. ? Per questioni di privacy non posso postare qui un file di esempio...

**Comment by Skullbock** [comment]
Salve, non abbiamo fatture di esempio da questo fornitore. 
Se preferisce può inviarmene una copia privatamente a [daniele at weble dot it] così da poter verificarlo

**Comment by itajackass** [comment]
Gliela invio subito. nel frattempo ho trovato un fix utilizzando openssl_cms_verify al posto di openssl_pkcs7_verify. Il problema  che openssl_cms_verify è utilizzabile solo con php >= 8

**Comment by Skullbock** [comment]
Confermo. Purtroppo però la libreria è compatibile con php 7.3+, quindi non possiamo "aggiungere" CMS lato php finchè non droppiamo il supporto per php 7.

Però questa parte è già gestita dalla libreria, è però necessario avere nel proprio sistema disponibile l'eseguibile `openssl`, in quanto usiamo il comando `openssl cms` per fare il parsing di questo tipo di file

Controlla quindi di avere openssl con CMS support (ad esempio su macos non è presente di default) e la libreria dovrebbe correttamente parsare il file

**Comment by Skullbock** [comment]
@itajackass puoi provare la branch https://github.com/fatturaelettronicaphp/FatturaElettronica/tree/feature/php8-cms-decoder e dirmi se su php 8.0 ti risulta funzionante?

Grazie

**Comment by Skullbock** [comment]
@itajackass chiudo la issue, non ho più ricevuto risposta per cui credo la cosa sia risolta

**Comment by itajackass** [comment]
Scusa il ritardo mi era sfuggita la notifica. Non funziona attualmente lo script per le fatture "problematiche" che ti dicevo.
Ho dovuto modificare il file CMSDecoder.php in questo modo:


```
namespace FatturaElettronicaPhp\FatturaElettronica\Decoder;

use FatturaElettronicaPhp\FatturaElettronica\Contracts\DigitalDocumentDecodeInterface;
use SimpleXMLElement;

class CMSDecoder implements DigitalDocumentDecodeInterface
{
    public function decode(string $filePath): ?SimpleXMLElement
    {
        $xmlPath = tempnam(sys_get_temp_dir(), basename($filePath));
        $pemPath = tempnam(sys_get_temp_dir(), basename($filePath));

		$p7mFilePath = $this->convertFromDERtoSMIMEFormat($filePath);

		// php 8 only
        if (
            function_exists('openssl_cms_verify') &&
			openssl_cms_verify($p7mFilePath, OPENSSL_CMS_NOVERIFY + OPENSSL_CMS_NOSIGS, $pemPath, array(__DIR__ . '/ca.pem'), __DIR__ . '/ca.pem', $xmlPath)
            
        ) {
            return (new XMLDecoder())->decode($xmlPath);
        }

        $exitCode = 0;
        $output   = [];
        exec(sprintf('openssl cms -verify -noverify -nosigs -in %s --inform DER  -out %s 2> /dev/null', $pemPath, $xmlPath), $output, $exitCode);

        if ($exitCode !== 0) {
            return null;
        }

        return (new XMLDecoder())->decode($xmlPath);
    }
	
	protected function convertFromDERtoSMIMEFormat(string $file): string
    {
        $pemPath = tempnam(sys_get_temp_dir(), basename($file));
        $to      = <<<TXT
MIME-Version: 1.0
Content-Disposition: attachment; filename="smime.p7m"
Content-Type: application/x-pkcs7-mime; smime-type=signed-data; name="smime.p7m"
Content-Transfer-Encoding: base64
\n
TXT;
        $from = file_get_contents($file);
        $to .= chunk_split(base64_encode($from));
        file_put_contents($pemPath, $to);

        return $pemPath;
    }
	
}
```

**Comment by Skullbock** [comment]
Ciao, ok grazie. Hai una fattura in questo formato da passarmi per poterla inserire nei test per validarne la funzionalità?

**Comment by itajackass** [comment]
inviata per email

**Comment by Skullbock** [comment]
Rilasciata la 2.4.0 con la modifica
