### ISSUE TITLE
Linee DatiRitenuta multiple 

### ISSUE THREAD

**Issue by vetarsonr** [fatturaelettronicaphp/FatturaElettronica#28]
Anzitutto, ottimo package!

Non trovo un modo per aggiungere nodi multipli di `DatiRitenuta`, è possibile?

Vedo solo i `setDeduction*` nel `DigitalDocumentInstance` che vanno poi a generare un unico nodo.

**Comment by Skullbock** [comment]
Grazie!

Può essere, probabilmente nella prima release dell'xml non era ripetibile. 

Te la senti di fare una PR con una proposta implementativa?

**Comment by vetarsonr** [comment]
Certo, l'avrei adattata comunque ma almeno così è ufficiale. 
i vecchi metodi per il set della singola ritenuta vuoi che li mantenga per la compatibilità?

**Comment by Skullbock** [comment]
Vorrei rilasciarla come minor quindi senza breaking changes. 

Manteniamoli si 👍🏻

**Comment by vetarsonr** [comment]
PR fatta

**Comment by Skullbock** [comment]
2.2.0 rilasciata. Grazie @vetarsonr
