### ISSUE TITLE
[FIX] Notice when import invoice

### ISSUE THREAD

**Issue by Scuottolinx** [fatturaelettronicaphp/FatturaElettronica#31]
Hi, 
in the src/Parser/XmlUtilities.php file I had to modify the extractValueFromXmlElement method because some invoices returned this error:
A non well formed numeric value encountered in

I leave you an excerpt of the invoice to make you understand the problem.
`... 
<PrezzoUnitario>2.70000 </PrezzoUnitario><PrezzoTotale>2.70 </PrezzoTotale>
...`

as you can see the problem lies in the spaces next to the numbers

i have resolved with:

`
        if ($convertToString) {
            return trim($value[0]->__toString());
        }
`
you could also think of doing it only for the figures, but in my opinion it makes no sense that no field starts and ends with white spaces

**Comment by Skullbock** [comment]
Thanks @Scuottolinx pushed a fix (2.2.2) and a related test.
Feel free to PR directly next time! :)

**Comment by Scuottolinx** [comment]
@Skullbock Thx a lot
