### ISSUE TITLE
proposta di modifica su getDate()->format()

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#33]
Salve non so se sia una buona idea ma la propongo.
Spesso e volentieri ci sono campi "date" facoltativi (esempio su OtherData).
Si potrebbe fare che chiamando il metodo, ad esempio:

    $valore =  $otherData->getDate()->format("Y-m-d");

nel caso il campo sia vuoto (null), il metodo format() restituisca null? Perchè attualmente si ha sempre:

    Fatal error: Uncaught Error: Call to a member function format() on null

Questo per evitare ogni volta di verificare che un campo "date" sia effettivamente compilato prima di chiamare la funzione format().

Grazie mille

**Comment by Skullbock** [comment]
Ciao, capisco la necessità ma vorrei evitare tale ridondanza, che sarebbe necessaria per ogni "nullable" object.

Se si usa PHP > 8, questa cosa si fa nativamente con il [Nullsafe Operator](https://www.php.net/releases/8.0/en.php#nullsafe-operator) `$date?->format('Y-m-d');`
