### ISSUE TITLE
Possibile bug su classle Representative 

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#36]
Salve non so se è un bug o meno,
ma credo che: 

    class Representative extends Billable implements ArrayableInterface, RepresentativeInterface

debba essere:

    class Representative extends BillablePerson implements ArrayableInterface, RepresentativeInterface

infatti se provo a scrivere:

       $rappresentanteFiscale = new FatturaElettronicaPhp\FatturaElettronica\Representative();
       $rappresentanteFiscale->setTitle("Mister");

ricevo errore su setTitle.

Mentre la stessa logica usata per:
  
       $intermediario = new FatturaElettronicaPhp\FatturaElettronica\Intermediary();
       $intermediario->setTitle("Mister");

funziona correttamente e infatti la class Intermediary estende BillablePerson

**Comment by Skullbock** [comment]
Risolto, grazie della segnalazione
