### ISSUE TITLE
Errore SDI in caso di piu' allegati

### ISSUE THREAD

**Issue by piccio85** [fatturaelettronicaphp/FatturaElettronica#37]
Ho la necessita' di inserire 2 allegati all'interno dell'XML

Attualmente la classe mi genera un XML cosi:
![image](https://user-images.githubusercontent.com/12586165/147610542-b251b2e1-c66e-42a5-b27d-6c6482ad9c47.png)

Quando invece dovrebbe essere cosi:
![image](https://user-images.githubusercontent.com/12586165/147610554-6d1876d3-40dd-494d-8347-53fd1237ce54.png)

Il codice che utilizzo per inserire gli allegati e' questo:

```
foreach ($listaAllegati as $a) {
    $attachemnt = new FatturaElettronicaPhp\FatturaElettronica\Attachment();
    $attachemnt->setName($a["NomeAttachment"]);
    $attachemnt->setDescription($a["NomeAttachment"]);
    $attachemnt->setAttachment($a["Attachment"]);
    $gD->addAttachment($attachemnt);
 }
```

Sbaglio qualcosa io nell'utilizzo della classe?
Io credo che il problema sia nella Classe **_AttachmentWriter_** in quanto la riga 

`$xml = $this->xml->addChild('Allegati');`

penso debba essere spostata all'interno del ciclo in modo da creare sempre un nuovo nodo

Vi incollo le specifiche dal sito dell'agenzia dell'entrate

![image](https://user-images.githubusercontent.com/12586165/147611492-57b362c4-7a23-4591-aab6-0a7d9abb8a12.png)

![image](https://user-images.githubusercontent.com/12586165/147611527-039744aa-7201-4bab-8ef4-23a96d48d459.png)

![image](https://user-images.githubusercontent.com/12586165/147611369-942be5eb-2aa9-41ba-9bb9-881181567e88.png)

**Comment by Skullbock** [comment]
Ciao @piccio85 grazie della segnalazione, risolto con la release 2.4.2
La prossima volta se riesci manda pure una PR direttamente con la risoluzione del problema, così rendiamo il processo ancora più veloce :)

Grazie!
