### ISSUE TITLE
Documentazione di esempio per creazione fattura

### ISSUE THREAD

**Issue by KristianLentino99** [fatturaelettronicaphp/FatturaElettronica#38]
Ciao, innanzitutto complimenti per il lavoro, davvero ben fatto!
Unica cosa, mi chiedevo se fosse possibile inserire nella doc la creazione di una fattura con la vostra libreria e magari se possibile aggiungere alle varie classi qualche commento che faccia capire che ripercussioni ha quella classe sulla fattura.

Grazie mille e ottimo lavoro!

**Comment by Skullbock** [comment]
@KristianLentino99 Grazie!

Per quanto riguarda la documentazione, sicuramente! E' nella nostra roadmap. Se nel mentre vuoi creare una piccola PR iniziale, i docs sono nel repository stesso

Per quanto riguarda i commenti, per ora la strategia è di usare il più possibile documentazione dedicata con esempi e autocompletamento degli IDE per i metodi
