### ISSUE TITLE
Formattare XML generato con indentazione

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#41]
Ho modificato il metodo wrhite() nel seguente file: DigitalDocumentWriter.php in modo da restituire un file XML con indentazione a capo per facilitare la leggibilità se può essere utile.

Magari ci sono altre strade, io ho usato questa:

       public function write($filePath): bool
    {
        if (stripos($filePath, '.xml') === false) {
            $filePath = $filePath . '/' . $this->document->generatedFilename();
        }
		
		$dom = dom_import_simplexml($this->generate()->xml())->ownerDocument;
		$dom->preserveWhiteSpace = false;
		$dom->formatOutput = true;
		return $dom->save($filePath);
    }

**Comment by Skullbock** [comment]
@itajackass buona idea.
Controlla se puoi la PR https://github.com/fatturaelettronicaphp/FatturaElettronica/pull/43 che propone tale integrazione, se ok la mergio e pubblico una nuova minor release

**Comment by itajackass** [comment]
Perfetto così con l'opzione di scegliere se volerla indentata oppure no. Ottimo

**Comment by itajackass** [comment]
ciao grazie degli altri aggiornamenti/fix. ho scaricato la nuova versione 2.5.0 ma la modifica del write per abilitare il pretty XML non risulta "committata" o sbaglio?

**Comment by Skullbock** [comment]
Committata nella 2.5.1. Nella 2.5.0 c'era solo per la semplificata non per la normale

**Comment by itajackass** [comment]
Ciao ho provato a lanciare:

    $eDocument->write("test.xml", true);

ma non mi formatta il file.
Ho provato a mettere un var_dump($format) e non so perchè... lo vede sempre a false anche se gli ho passato il true...

**Comment by itajackass** [comment]
forse c'è da modificare anche il file: DigitalDocumentWriterInterface.php

**Comment by Skullbock** [comment]
Fixato in 2.5.2
