### ISSUE TITLE
Campo 2.1.9.1.4   <NumeroLicenzaGuida> mancante

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#42]
Sembra non essere gestito il campo:

    2.1.9.1.4   <NumeroLicenzaGuida>

**Comment by Skullbock** [comment]
Pubblicata la 2.4.3 con il supporto al campo

**Comment by itajackass** [comment]
ho provato ad utilizzare:

       $datiTrasporto = new FatturaElettronicaPhp\FatturaElettronica\Shipment();
       $datiAnagraficiVettore = new FatturaElettronicaPhp\FatturaElettronica\Shipper();
       ....
       $datiAnagraficiVettore->setLicenseNumber("123456");
       $datiTrasporto->setShipper($datiAnagraficiVettore);

Ma nel file xml il campo NumeroLicenzaGuida non viene generato. Non so se è un mio errore

**Comment by Skullbock** [comment]
Rilasciata la 2.5.0 con il fix
