### ISSUE TITLE
Possibile errore in PaymentDetails.php

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#44]
Nel file PaymentDetails.php sono presenti i metodi:

    getTerms()
   
    setTerms($terms)

ma credo siano dei refusi in quanto il metodo setTerms() è correttamente utilizzato in PaymentInfo.php. Ho provato comunque ad utilizzarlo con la classe PaymentDetails (per vedere che risultato dava) ma di fatto non scrive nulla nel file xml

**Comment by Skullbock** [comment]
Rilasciata la 2.5.0 con il fix
