### ISSUE TITLE
$lineNumberReference in ShippingLabel dovrebbe essere un array

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#45]
la variabile $lineNumberReference nella classe ShippingLabel dovrebbe essere un array in quanto da specifiche tecniche il campo

      2.1.2.1   <RiferimentoNumeroLinea>

ha molteplicità 0.N

**Comment by Skullbock** [comment]
Rilasciata la 2.5.0 con il fix
