### ISSUE TITLE
errore in $eDocument->isValid()

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#47]
Ciao ho provato a validare un xml, con:

     var_dump($eDocument->isValid());

ma ricevo warning:

      Warning: DOMDocument::schemaValidateSource(): Invalid Schema in C:\wamp64\www\fatturaelettronicaphp\vendor\fatturaelettronicaphp\fattura-elettronica\src\Validator\DigitalDocumentValidator.php on line 43

con validazione "false"

se faccio un var_dump di:
   
     $errors = $eDocument->validate()->errors();

visualizzo:

      '{http' => string '/www.w3.org/2001/XMLSchema}element', attribute 'ref': The QName value '{http://www.w3.org/2000/09/xmldsig#}Signature' does not resolve to a(n) element declaration.

**Comment by Skullbock** [comment]
Vedo che stai usando windows. Quell'errore da come problema di caricamento il file `core.xsd` che carichiamo localmente, forse il tuo env php ha problema nel caricare quel file?

Prova la branch fix/xsd per vedere se lo risolve, altrimenti ho bisogno di più info sul perchè la tua installazione di php su windows non carica correttamente il file

**Comment by itajackass** [comment]
ho provato l'altra branch senza successo.

Se provo a modificare il metodo (vedi linea commentata):


     protected function getSchema(): string
    {
        //$schemaFile = $this->document->isSimplified() ? 'semplificata_1.0.xsd' : 'pa_1.2.1.xsd';
        $schemaFile = $this->document->isSimplified() ? 'semplificata_1.0.xsd' : 'core.xsd';
        $xsd = file_get_contents(__DIR__ . '/xsd/' . $schemaFile);

        $xmldsigFilename = __DIR__ . '/xsd/xmldsig-core-schema.xsd';
        $xsd = preg_replace('/(\bschemaLocation=")[^"]+"/', sprintf('\1%s"', $xmldsigFilename), $xsd);

        return $xsd;
    }


il warning se ne va, ma ho come risultato di  $errors = $eDocument->validate()->errors();:


      {http' => string '/ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}FatturaElettronica': No matching global declaration available for the validation root.

**Comment by itajackass** [comment]
a dir il vero non avevo ancora usato la validazione prima d'ora perchè stavo ancora lavorando sulla creazione dell' xml. c'è modo di recuperare vecchie releases così provo?

**Comment by Skullbock** [comment]
Sono tutte taggate su git e le puoi recuperare sia da GIT che da composer

**Comment by itajackass** [comment]
si le sto provando con composer... sono andato a ritroso fino alla 2.0 ma nulla da fare...  mi sembra di aver letto sul git dell'autore del codice che si occupa della validazione, che su win proprio non c'è verso di farlo andare sembra

**Comment by Skullbock** [comment]
Sembra che ci sia riuscito usando il file path invece della stringa source.
https://github.com/fatturaelettronicaphp/FatturaElettronica/actions/runs/1683442542

Prova di nuovo la branch `fix/xsd`

**Comment by itajackass** [comment]
Magnifico! Funziona!

**Comment by Skullbock** [comment]
Rilasciato nella 2.5.3
