### ISSUE TITLE
NumeroCivico: This element is not expected

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#49]
Ciao se provo ad indicare il numero civico e/o la provincia in:

  DatiTrasporto -> IndirizzoResa

ho errore validazione:

      NumeroCivico: This element is not expected
      Provincia: This element is not expected

con:

     $datiTrasporto = new FatturaElettronicaPhp\FatturaElettronica\Shipment();
     ....
     $datiTrasportoIndirizzoResa = new FatturaElettronicaPhp\FatturaElettronica\Address();
     $datiTrasportoIndirizzoResa->setStreetNumber(1);
     $datiTrasportoIndirizzoResa->setState("PR");
     ...
     $datiTrasporto->setReturnAddress($datiTrasportoIndirizzoResa);

Eppure da specifiche tecniche questi 2 campi sono presenti

**Comment by itajackass** [comment]
Stesso problema con:

     $rigaBeniServiziAltriDatiGestionali->setNumber(123);

con errore:

     'RiferimentoNumero'' => string 'This element is not expected.

**Comment by Skullbock** [comment]
Risolto nella 2.6.0.

Grazie @itajackass per tutti i suggerimenti. Se te la senti, invia pure delle PR per sistemare queste cose quando le trovi, aiuta molto sia con i corretti "contributors" della libreria che con la velocità di gestione.
