### ISSUE TITLE
Typo error: DatiContratti invece di DatiContratto

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#50]
C'è un typo error ed annotazioni (poco importa) in GeneralDataWriter.php:

Questo:

      /* Dati convenzioni */
        foreach ($this->body->getContracts() as $dataContract) {
            $this->addExternalDocument($dataContract, $generalData->addChild('DatiContratti'));
        }

        /* Dati contratti */
        foreach ($this->body->getConventions() as $dataContract) {
            $this->addExternalDocument($dataContract, $generalData->addChild('DatiConvenzione'));
        }

        /* Dati contratti */
        foreach ($this->body->getReceipts() as $dataContract) {
            $this->addExternalDocument($dataContract, $generalData->addChild('DatiRicezione'));
        }

dovrebbe essere:

 
      /* Dati contratto */
        foreach ($this->body->getContracts() as $dataContract) {
            $this->addExternalDocument($dataContract, $generalData->addChild('DatiContratto'));
        }

        /* Dati convenzione */
        foreach ($this->body->getConventions() as $dataConvention) {
            $this->addExternalDocument($dataConvention, $generalData->addChild('DatiConvenzione'));
        }

        /* Dati ricezione */
        foreach ($this->body->getReceipts() as $dataReceipt) {
            $this->addExternalDocument($dataReceipt, $generalData->addChild('DatiRicezione'));
        }

**Comment by Skullbock** [comment]
Risolto nella 2.6.1

Grazie @itajackass per tutti i suggerimenti. Se te la senti, invia pure delle PR per sistemare queste cose quando le trovi, aiuta molto sia con i corretti "contributors" della libreria che con la velocità di gestione.
