### ISSUE TITLE
Errore formattazione decimali: Sconto pagamento anticipato e CapitaleSociale

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#52]
Se metto:

      $datiPagamentoDettagli->setEarlyPaymentDiscount(10.00);

ricevo errore validazione:

      'ScontoPagamentoAnticipato'' => string '[facet 'pattern'] The value '10' is not accepted by the pattern '[\-]?[0-9]{1,11}\.[0-9]{2}'.

sembra che lo script rimuova i decimali che sono necessari.... infatti se mettessi 10.01 la validazione è ok.

Il problema è presente anche in: CapitaleSociale .... non ho ancora verificato eventuali altri campi per ora

**Comment by itajackass** [comment]
Anche in:

      $datiTrasporto->setWeight(170); //peso lordo
      $datiTrasporto->setNetWeight(150.00); //peso netto

forse poi è utile convertire in automatico un valore passato senza decimali, aggiungendoli in automatico

**Comment by Skullbock** [comment]
Risolto nella 2.6.0. 

Grazie @itajackass per tutti i suggerimenti. Se te la senti, invia pure delle PR per sistemare queste cose quando le trovi, aiuta molto sia con i corretti "contributors" della libreria che con la velocità di gestione.

**Comment by itajackass** [comment]
Ciao non sono molto ferrato con github.. se trovo altri problemi provo a capire come si fa.grazie
