### ISSUE TITLE
[Feature] validazione dati con messaggi user friendly

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#54]
Ciao chiedo se esiste un modo per mostrare all'utente finale dei messaggi personalizzati (quindi in italiano, comunque personalizzabili...) in caso di errore nella validazione di un dato.

Faccio un esempio:

Se provo a inserire un C.F. volutamente errato (1 carattere in più) nell'**intermediario**:

        ...
        $intermediario->setFiscalCode("AAABBB86C20G123FF");
	$eDocument->setIntermediary($intermediario);

e faccio validazione, ricevo:

      'CodiceFiscale'' => string '[facet 'pattern'] The value 'AAABBB86C20G123FF' is not accepted by the pattern '[A-Z0-9]{11,16}'.

In primo luogo sarebbe utile sapere di quale codice fiscale stiamo parlando (ce ne sono diversi all'interno dell'xml). in questo caso sarebbe dell'intermediario **<1.5.1.2>**.

E trovare il modo per avere un messaggio personalizzato, se possibile. Molti utenti finali noto che non capiscono il significato del messaggio.

Hai qualche idea? Grazie mille

**Comment by Skullbock** [comment]
Ciao. La validazione, vista la sua complessità e il fatto che viene poi validata nello stesso modo dallo SDI, è fatta tramite il file XSD (Xml Schema) automaticamente, quindi quello è il messaggio che il validatore è in grado di ritornare di default. 

Se vuoi personalizzarlo, devi intercettare i messaggi, usare la chiave `CodiceFiscale` e poi inserire tu un messaggiò personalizzato, che spieghi qual'è la regola da rispettare.

Per i valori "lista", c'è il metodo `values` per ognuno degli `Enum` disponibili, anch'esso preso dallo schema. In questo caso però c'è una descrizione in italiano del valore, comoda da usare per esempio per costruire un "select" di valori da far scegliere ad un utente.

Per esempio:

```php
VatNature::values();
```

ritorna 
N1: Escluse ex. art. 15 del D.P.R. 633/1972

Etc
