### ISSUE TITLE
Dati formato xs:normalizedString

### ISSUE THREAD

**Issue by Andicot** [fatturaelettronicaphp/FatturaElettronica#55]
Complimenti per la libreria.
Ho notato che nei dati stringa il cui formato ammesso è xs:normalizedString, le lettere accentate vengono sostituite da un ?.
In realtà tutti i caratteri isBasicLatin sono ammessi.

**Comment by Skullbock** [comment]
Grazie mille!

Intendi in lettura o scrittura del documento?

**Comment by Andicot** [comment]
In scrittura.

**Comment by Skullbock** [comment]
E' stato più complesso del previsto, ma ora dovrebbero essere supportati correttamente.
La libreria farà encoding in ASCII con traslitterazione solo se la stringa contiene caratteri non latin1
Ho aggiunto anche un test che validi tale casistica.

Rilasciata la 2.6.2 con il fix, se puoi confermare che è tutto ok :)

**Comment by Andicot** [comment]
Sei molto efficiente.
Confermo che mi sembra tutto ok!
