### ISSUE TITLE
Errore sanitizeText in NumeroDDT

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#56]
Ciao ho il seguente campo 

      2.1.8.1   <NumeroDDT>

compilato così: 

      20/2021/G

ma ricevo errore: 

      Fatal error: Uncaught TypeError: FatturaElettronicaPhp\FatturaElettronica\Utilities\SimpleXmlExtended::sanitizeText(): Argument #1 ($text) must be of type string, null given, called in C:\wamp64\www\test\vendor\fatturaelettronicaphp\fattura-elettronica\src\Writer\Body\GeneralDataWriter.php on line 208

**Comment by itajackass** [comment]
ho aperto una pullrequest ma non le ho mai utilizzate non so se ho fatto correttamente...

**Comment by Skullbock** [comment]
Vedi #57

**Comment by Skullbock** [comment]
Ho aggiunto un test [https://github.com/fatturaelettronicaphp/FatturaElettronica/blob/master/tests/CustomWriteDigitalDocumentTest.php#L123](https://github.com/fatturaelettronicaphp/FatturaElettronica/blob/master/tests/CustomWriteDigitalDocumentTest.php#L123) e passano correttamente. Se sicuro che stai usando l'ultima versione?

**Comment by itajackass** [comment]
Ciao ho indagato meglio... allora durante la creazione di un xml nessun problema... il problema mi si pone aprendo un xml e utilizzando il serialize():

    $digitalDocument = FatturaElettronicaPhp\FatturaElettronica\DigitalDocument::parseFrom($file);
    $xml = $digitalDocument->serialize();
    var_dump($xml);

**Comment by itajackass** [comment]
riporto tutto il messaggio di errore:



```
Fatal error: Uncaught TypeError: FatturaElettronicaPhp\FatturaElettronica\Utilities\SimpleXmlExtended::sanitizeText(): Argument #1 ($text) must be of type string, null given, called in C:\wamp64\www\test\vendor\fatturaelettronicaphp\fattura-elettronica\src\Writer\Body\GeneralDataWriter.php on line 208 and defined in C:\wamp64\www\test\vendor\fatturaelettronicaphp\fattura-elettronica\src\Utilities\SimpleXmlExtended.php on line 33


TypeError: FatturaElettronicaPhp\FatturaElettronica\Utilities\SimpleXmlExtended::sanitizeText(): Argument #1 ($text) must be of type string, null given, called in C:\wamp64\www\test\vendor\fatturaelettronicaphp\fattura-elettronica\src\Writer\Body\GeneralDataWriter.php on line 208 in C:\wamp64\www\test\vendor\fatturaelettronicaphp\fattura-elettronica\src\Utilities\SimpleXmlExtended.php on line 33
```

**Comment by itajackass** [comment]
ho provato anche a settare un numeroDDT solo numerico:

   123

ma ricevo sempre errore di cui sopra quindi gli slash non sono il problema

**Comment by itajackass** [comment]
ho fatto altre prove con il mio script sopra e noto che i seguendi codici

    $ddtData->addChild('NumeroDDT', $documentDdt->getDocumentNumber());

        if ($documentDdt->getDocumentDate()) {
            $ddtData->addChild('DataDDT', $documentDdt->getDocumentDate()->format('Y-m-d'));
        }

contenuti nel metodo:

    addShippingLabelsData

(anche se come vedi ho tolto il sanitizeText) restituiscono sempre NULL nonostante l' XML sia compilato con tali dati NumeroDDT e DataDDT

**Comment by itajackass** [comment]
se metto valori hardcoded come:

    $ddtData->addChild('NumeroDDT', 50);
    $ddtData->addChild('DataDDT', "2020-01-01");

allora funziona, altrimenti non riesce a recuperare i valori da xml

**Comment by itajackass** [comment]
il var_dump di $e = FatturaElettronicaPhp\FatturaElettronica\DigitalDocument::parseFrom($file);

si nota che non riesce a recuperare i campi documentNumber e documentDate


        protected 'shippingLabels' => 
            array (size=1)
              0 => 
                object(FatturaElettronicaPhp\FatturaElettronica\ShippingLabel)[61]
                  protected 'documentNumber' => null
                  protected 'documentDate' => null
                  protected 'lineNumberReferences' => 
                    array (size=1)
                      0 => string '1' (length=1)

**Comment by itajackass** [comment]
trovato errore, creato nuovo PR
