### ISSUE TITLE
File non conforme al formato

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#59]
Ciao ho finito di migrare il mio vecchio script di generazione xml, con il tuo ma inviando il file all' SDI (nello specifico parlo del servizio aruba) ricevo come notifica di scarto:

       File non conforme al formato : schemaLocation value = 'http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2' must have even number of URI's. riga: 2 - colonna: 295

Hai qualche idea?

**Comment by itajackass** [comment]
Ciao ora ti mando il file via email, ad ogni modo guardando un file che generavo prima rispetto ad ora che uso il tuo script, noto solo questa differenza:

Miei vecchi file che SDI accettava:

    <?xml version="1.0" encoding="UTF-8"?>
<p:FatturaElettronica versione="FPR12" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:p="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2 http://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2/Schema_del_file_xml_FatturaPA_versione_1.2.xsd">


File generati ora:

     <?xml version="1.0" encoding="UTF-8"?>
<p:FatturaElettronica versione="FPR12" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:p="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2">
   

Appena riesco provo ad usare lo script di invio che mi hai indcato, nell'ambiente di test aruba!

**Comment by Skullbock** [comment]
Grazie. Sembra che non si riesca a registrarsi all'ambiente di test aruba se non si è utenti paganti del servizio, giusto?

**Comment by itajackass** [comment]
noi abbiamo account business. non saprei se aprano ambienti di test su richiesta... ad ogni modo il problema non sembra essere di aruba in quanto aruba vedo che mi accetta il file e lo invia all' SDI. è l'SDI che mi scarta la fattura... ora ho provato a modificare il DIgitalDOcumentWriter.php e reinviare la fattura... tra poche ore vedrò se me la accetta e al massimo faccio una PR

**Comment by Skullbock** [comment]
Ottimo, grazie.
Noi siamo su teamsystem quindi non abbiamo modo di controllare la parte Aruba, per quello chiedevo

**Comment by itajackass** [comment]
Ciao confermo che con la modifica che ho proposto la fattura viene consegnata. Ho creato PR

**Comment by Skullbock** [comment]
Grazie, risolto in #60
