### ISSUE TITLE
PrezzoTotale si ferma a 2 decimali

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#61]
Ciao, da specifiche tecniche, anche il campo PrezzoTotale ammettere fino a 8 decimali. Ho notato invece che durante la generazione di un xml viene troncata a 2 decimali.
Credo possa essere un problema per chi emette fatture ad esempio sui prezzi benzina dove è utile avere un numero maggiore di decimali.

Un esempio su una fattura che ho creato:

    quantità (5.6) X prezzo unitario (2.3174356) = prezzo totale (12.97763936)

mentre nell'XML mi viene approssimato a 12.98

nel dettaglio:

Note sulla Versione V.2021
Con la nuova versione, a pieno regime dal 01/01/2021, il numero dei decimali accettabili passa da 2 ad 8, ciò in analogia con i nodi <Arrotondamento>, <PrezzoUnitario>, <Quantita> e <PrezzoTotale>. 

recuperata da: https://fex-app.com/FatturaElettronica/FatturaElettronicaBody/DatiBeniServizi/DettaglioLinee/ScontoMaggiorazione/Importo

**Comment by Skullbock** [comment]
Si, in effetti non è stata aggiornata la cosa dopo il 1/1/2021 nella libreria. 
Te la senti di fare una PR? La chiamata `SimpleXmlExtended::sanitizeFloat` accetta un secondo parametro che sono il numero di decimali accettati, e può essere usata per lo scopo

**Comment by itajackass** [comment]
ciao mi sai dire se poi la mia PR era giusta riguardo ai decimali?
