### ISSUE TITLE
eccezione parsing fatture Enel Energia S.p.a

### ISSUE THREAD

**Issue by danilokeliweb** [fatturaelettronicaphp/FatturaElettronica#68]
Salve, in primis volevo fare i complimenti per l'ottimo lavoro per questo utilissimo pacchetto per gestire la fatturazione elettronica. Volevo però segnalare un problema pressoché costante nel fare il parsing delle fatture provenienti da Enel Energia S.p.a (sì, esatto, solo da questo Cedente/Prestatore). Viene generata sempre una eccezione InvalidXmlFile dalla classe DigitalDocumentParser.php. Ma con qualsiasi tool online riesco a leggere tranquillamente il P7M, anche aprendo l'originale in vim non vedo problemi si struttura XML. Allego screen e file P7M di esempio che genera questo errore (per questioni di privacy, ho modificato alcuni dati presenti in fattura mettendoli palesementi finti). Saluti, Danilo.
[IT06655971007_12345.xml.zip](https://github.com/fatturaelettronicaphp/FatturaElettronica/files/8244272/IT06655971007_12345.xml.zip)
![Screenshot 2022-03-14 at 12-18-39 Whoops! There was an error](https://user-images.githubusercontent.com/50329010/158162057-0d3794dc-c617-4840-b874-2b209ab82889.png)

**Comment by KristianLentino99** [comment]
Ciao @danilokeliweb , per caso hai provato a rinominare il file in .xml normale e rimuovere i caratteri speciali presenti a inizio file?
![image](https://user-images.githubusercontent.com/60007558/158187130-6be31bda-3047-4240-90fb-032bbe57652b.png)

**Comment by danilokeliweb** [comment]
> Ciao @danilokeliweb , per caso hai provato a rinominare il file in .xml normale e rimuovere i caratteri speciali presenti a inizio file? ![image](https://user-images.githubusercontent.com/60007558/158187130-6be31bda-3047-4240-90fb-032bbe57652b.png)

Ciao @KristianLentino99 , si' diciamo che questa procedura l'ho gia' tentata cercando di trattare i file P7M, ovviamente di ottiene un XML pulito e poi libero da poter essere processato come meglio si crede. Ma mi chiedevo come mai la classe in se' non riuscisse a gestire bene questo tipo di file. Andando piu' nell specifico, penso sia un problema di allegati, cioe' l'eccezione che si ottiene e' <NomeAttachment> is required o <Attachment> is required, non riconoscendo come stringa forse un nome di file tipo quello inserito (SHA256_PDF_004208027205 o simili).

**Comment by danilokeliweb** [comment]
> 



> Ciao @KristianLentino99 @danilokeliweb
> 
> Credo che ormai Enel sia la bestia nera per le fatture elettroniche. Nell'ultimo anno gli unici problemi riscontrati sono sempre relativi a questo fornitore...
> 
> Dalla nostra test suite che ha 2 o 3 esempi loro non ho errori di lettura, ti chiedo se riesci a girarmi (via mail visto che sono documenti privati) il file che ti dà errore, in modo da aggiungerlo alla test suite e verificare che problemi potrebbero esserci
> 
> Grazie

Ciao @Skullbock , gentilissimo, si' ti confermo che a parte queste fatture dell'Enel, il pacchetto e' veramente perfetto, e ti ringrazio ancora a nome di tutti. Ottimo allora, ti invio via email 2 o 3 fatture in originale, cosi' da permetterti di fare ulteriori test. Un saluto e grazie per la celere risposta.

**Comment by Skullbock** [comment]
Ho aggiunto la fattura incriminata e effettivamente i test falliscono.
La cosa più strana è che in locale (macosx) i test passano. Per fortuna c'è la CI 👍 

Vedo cosa può essere, se trovate ancora voi una soluzione elegante fate pure una PR!

**Comment by Skullbock** [comment]
https://github.com/fatturaelettronicaphp/FatturaElettronica/runs/5540095046?check_suite_focus=true

**Comment by Skullbock** [comment]
Ok, dai test si evince chiaramente che per decodificare le fatture di Enel è necessario:

- Avere php8+ e open_ssl abilitato correttamente per eseguire `openssl_cms_verify`
- Oppure avere installato sul sistema e essere in grado di eseguire il comando shell `openssl cms verify`.

Se nessuna delle due è abilitata, non è possibile decodificare le fatture CMS (quelle di enel)
Se mi confermi, chiudo la task così perchè è relativa a configurazione server side

**Comment by danilokeliweb** [comment]
@Skullbock sì va bene, chiudiamo pure, l'importante è aver trovato la causa, farò dei test in locale e su una VPS per risolvere definitivamente. Grazie ancora.

**Comment by Skullbock** [comment]
Ottimo @danilokeliweb 

Se dai tuoi test risulta la cosa, riesci a inviare una PR al README / documentazione per inserire una nota in merito?

Grazie!

**Comment by danilokeliweb** [comment]
@Skullbock certamente, ci lavoro su e appena ho qualcosa di concreto aggiorno tutto e invio PR.
