### ISSUE TITLE
errore test

### ISSUE THREAD

**Issue by zfranco55** [fatturaelettronicaphp/FatturaElettronica#75]
premettendo che non sono un esperto, vorrei chiedere a cosa è dovuto il seguente errore, quando eseguo composer test.
`[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "test" is not defined. `
Il programma viene eseguito in ambiente bitnami LAMP (equivalente di xampp).
Se qualcuno mi puo dire dove l'errore che faccio lo ringrazio.

**Comment by Skullbock** [comment]
Ciao @zfranco55 
cosa stai cercando di fare?

Nel caso specifico, il comando `test` è valido solo se scarichi questo repository con git, fai `composer install` e poi lanci `composer test`, ed è usato da noi sviluppatori della libreria, per verificare che la libreria stessa funzioni ancora.

Gli utilizzatori della libreria stessa non hanno necessità / modo di eseguirlo.
Cosa stai cercando di fare?

**Comment by zfranco55** [comment]
per il progetto che sto cercando di fare, prevede di scaricare (ogni
trimestre) dall'agenzia delle entrate le fatture emesse, ricevute ed i
corrispettivi.
Cercavo una libreria che mi permettesse di estrarre alcuni dati dalle
fatture (soprattutto i file p7m), per inserirli un mio Db.

Il giorno lun 16 mag 2022 alle ore 18:05 Daniele Rosario <
***@***.***> ha scritto:

**Comment by Skullbock** [comment]
Questa libreria può aiutarti nella seconda parte cioè nell'estrarre dati dalle fatture, anche in p7m. 

Installa la libreria tramite composer (se non è uno strumento con cui sei familiare, trovi veramente molte guide online su com'è cominciare con un progetto composer) e segui poi la documentazione per leggerne i dati.
