### ISSUE TITLE
Metodo getBankName()

### ISSUE THREAD

**Issue by MatteoZandara** [fatturaelettronicaphp/FatturaElettronica#76]
@Skullbock Salve, possibile che il metodo **getBankName()** della classe **PaymentDetails** ritorni sempre null? Anche se nella fattura il campo risulta valorizzato?

**Comment by Skullbock** [comment]
Grazie per la segnalazione, abbiamo rilasciato la 2.6.6 con questo e altri fix, e i relativi test
