### ISSUE TITLE
Mancanza campo RiferimentoAmministrazione nel parsing linee beni/servizi

### ISSUE THREAD

**Issue by SorPampurio** [fatturaelettronicaphp/FatturaElettronica#80]
Sembra abbiate dimenticato di parsare il campo RiferimentoAmministrazione sulle linee beni/servizi.

$value = $this->extractValueFromXmlElement($xml, 'RiferimentoAmministrazione');
$instance->setAdministrativeContact($value);

src/Parser/Body/LinesParser.php

**Comment by Skullbock** [comment]
Aggiunto e pubblicato nella 2.6.7
