### ISSUE TITLE
Fattura formato strano da nuovo fornitore

### ISSUE THREAD

**Issue by itajackass** [fatturaelettronicaphp/FatturaElettronica#82]
Ciao ti scrivo perchè nel gestionale abbiamo un nuovo fornitore che ci sta inviando delle fatture XML (transitate correttamente dal sistema ARUBA) ma che hanno un problema nel campo allegati... infatti è presente solo il tag

    <Attachment/>

senza la relativa apertura tag. Di fatto quindi è indicata la presenza di un allegato con il suo campo nome... ma nulla riguardo il contenuto!

Non so perchè Aruba non abbia scartato il file sinceramente.... ho provato a caricare il file su qualche sito di verifica xml ed in effetti tutti me lo rifiutano.

Siccome non posso postarlo qui per problemi di privacy dati sensibili.. potresti lasciarmi la tua email così che tu possa verificare se si tratti effettivamente di un errore di compilazione da parte del fornitore?

Ad ogni modo faccio presente il problema anche ad Aruba...

Grazie

EDIT: ho dato in pasto il file anche a DIKE, al contrario DIKE mi dice che il file è ok nonostante l'incongruenza del tag "orfano"

**Comment by itajackass** [comment]
Allego la mia funzione per visualizzare un qualsiasi file xml/p7m con un foglio di stile preimpostato:

                $path_to_file_xml = "c:/test/prova.xml";

                $digitalDocument = FatturaElettronicaPhp\FatturaElettronica\DigitalDocument::parseFrom($path_to_file_xml);
		
		$xml = $digitalDocument->serialize();

		$stringXML = $xml->asXML();

		$XML = new DOMDocument();

		$XML->loadXML( $stringXML );

		$xslt = new XSLTProcessor();

		$XSL = new DOMDocument();

                $XSL->load( 'style.xsl' );

		$xslt->importStylesheet( $XSL );

		print $xslt->transformToXML( $XML );

**Comment by Skullbock** [comment]
Ciao, purtroppo non diamo supporto di questo tipo un una libreria open source per problemi come questi.
Se il file xml che ricevi è invalido credo che la strata migliore sia di sentire chi ti invia la fattura per capire se quella che hanno inviato è quella che ricevi, quindi se l'errore sta nella produzione lato loro dell'xml o nella gestione di aruba, e riportare conseguentemente il problema

**Comment by itajackass** [comment]
Ciao ho ricevuto risposta da Aruba il quale mi dicono che loro ovviamente riportano il file tale e quale come ricevuto da SdI... e il tag selfclosed <Attachment/> è valido. Da specifiche tecniche è indicato che Attachment è obbligatorio ma è presente solo un limite di dimensione massima... ma non quella minima. Di fatto è possibile l'inserimento di un Attachment (obbligatorio) anche vuoto (dimensione = 0). Ora guardo se riesco a fare una modifica per soddisfare tale casistica e al massimo faccio una pull request

**Comment by itajackass** [comment]
Ciao avevo fatto un nuovo pull basato sulla casistica accettata: cioè Attachment obbligatorio come esistenza del campo...ma con possibilità che sia valorizzato vuoto (come da tracciato AdE)
Non so se sei riuscito a visionarlo... con tale modifica ora riesco a "parsare" anche gli xml che presentano il campo autochiuso "<Attachment/>"
