### ISSUE TITLE
RiferimentoNumeroLinea in Parsing DatiDDT estrapola solo la prima corrispondenza

### ISSUE THREAD

**Issue by brokenicedeveloper** [fatturaelettronicaphp/FatturaElettronica#92]
La procedura di parsing del blocco DatiDDT non tiene conto della possibile molteplicità del campo RiferimentoNumeroLinea, pertanto viene preso in considerazione solo il primo riscontro.

Di seguito la funzione in questione:
```
protected function extractShippingLabelInformationsFrom($order): ShippingLabel
    {
        $instance = new ShippingLabel();

        $value = $this->extractValueFromXmlElement($order, 'RiferimentoNumeroLinea');
        $instance->setLineNumberReference($value);

        $value = $this->extractValueFromXmlElement($order, 'NumeroDDT');
        $instance->setDocumentNumber($value);

        $value = $this->extractValueFromXmlElement($order, 'DataDDT');
        $instance->setDocumentDate($value);

        return $instance;
    }
```

**Possibile blocco DatiDDT**:
```
...
</DatiDDT>
<DatiDDT>
        <NumeroDDT>123456</NumeroDDT>
        <DataDDT>2023-04-21</DataDDT>
        <RiferimentoNumeroLinea>10</RiferimentoNumeroLinea>
        <RiferimentoNumeroLinea>11</RiferimentoNumeroLinea>
        <RiferimentoNumeroLinea>12</RiferimentoNumeroLinea>
        <RiferimentoNumeroLinea>13</RiferimentoNumeroLinea>
 </DatiDDT>
```

**Comportamento desiderato**:
La funzione ShippingLabel@getLineNumberReferences restituisce un'array di 4 elementi ([10, 11, 12, 13]).

**Attuale comportamento**:
La funzione ShippingLabel@getLineNumberReferences restituisce un'array di 1 elemento ([10]).

**Versione in uso**: 2.6.11

Grazie in anticipo.

**Comment by Skullbock** [comment]
Ciao, grazie della segnalazione
Puoi aprire una PR per risolvere la cosa?

**Comment by Skullbock** [comment]
Grazie della PR e del report dettagliato.
Ho mergiato, sistemato lo stile per essere in linea con il resto della libreria e aggiunto un test dedicato che puoi trovare [Qui](https://github.com/fatturaelettronicaphp/FatturaElettronica/blob/master/tests/ParseDigitalDocumentTest.php#L173)

Rilasciata la 2.6.12 con il fix
