### ISSUE TITLE
L'estrazione del file fattura.xml dal file fattura.xml.p7m non rispetta il contenuto originale del file.

### ISSUE THREAD

**Issue by uomopalese** [fatturaelettronicaphp/FatturaElettronica#96]
Il caso riguarda alcune particolari fatture elettroniche, come quella del SERVIZIO ELETTRICO NAZIONALE.
In queste fatture nel `<DettaglioLinee>...</DettaglioLinee>` **non è presente** il tag `<Quantita>....</Quantita>`, probabilmente perchè il `<PrezzoUnitario>2.11000000</PrezzoUnitario>`  corrisponde sempre al `<PrezzoTotale>2.11000000</PrezzoTotale>`. 
Il tag `<Quantita>....</Quantita>` però viene automaticamente aggiunto in fase di estrazione del file fattura.xml dal file fattura.xml.p7m come `<Quantita>0.00000000</Quantita>`. 
Ne consegue che una verifica del file restituisce l'errore 
` 2.2.1.11 <PrezzoTotale> non calcolato secondo le regole definite nelle specifiche tecniche` 
per ogni linea contenuta in fattura, poichè appunto il prezzo unitario viene moltiplicato per `0.00000000`, non corrispondendo più al prezzo totale.

Es.:
`$xml = 'fattura.xml.p7m'; `
`$eDocument = DigitalDocument::parseFrom($xml);`
`$eDocument->write('fattura.xml');`

**Comment by Skullbock** [comment]
Ciao @uomopalese hai per caso un file di esempio così da poter testare la cosa?
Se contiene dati personali puoi anonimizzarli prima o inviarmeli via mail così da pter testare la cosa

Grazie

**Comment by uomopalese** [comment]
Ti ho girato una mail in privato

**Comment by Skullbock** [comment]
2.6.14 dovrebbe risolvere il problema menzionato
